name: UI Tests (Selenium + Pytest)

on:
  push:
    branches: [ "main", "master" ]
  pull_request:

env:
  PYTHONPATH: .   # để từ root import được src.*

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Setup Chrome
        id: chrome
        uses: browser-actions/setup-chrome@v1
        # outputs.chrome-path sẽ là đường dẫn chrome thực tế

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pytest (headless) and generate HTML report
        env:
          CHROME_BIN: ${{ steps.chrome.outputs.chrome-path }}
          BASE_URL: https://opensource-demo.orangehrmlive.com/
          USERNAME: Admin
          PASSWORD: admin123
          HEADLESS: "true"
        run: |
          mkdir -p reports
          pytest --html=reports/report.html --self-contained-html

      - name: Upload HTML report artifact
        uses: actions/upload-artifact@v4
        with:
          name: ui-report
          path: reports/report.html
